# language.py

lang = {
    "English": {
        "settings": "Settings",
        "password_rules": "Password Rules",
        "minimum_length": "Minimum Length",
        "require_number": "Require Numbers",
        "require_upper_lower": "Require Uppercase & Lowercase",
        "require_length": "Require Minimum Length (12+)",
        "require_not_common": "Require Non-Common Password",
        "require_not_repeated": "Require No Repeated Characters",
        "title": "🔐 Password Strength Checker",
        "subtitle": "Analyze your password security or generate a strong one.",
        "password": "Enter Password",
        "check": "Check Strength",
        "empty": "Please enter a password to evaluate!",
        "result": "Evaluation Result",
        "strength": "Strength",
        "score": "Score",
        "reason": "Details & Feedback",
        "suggestions": "Security Suggestions",
        "tips": "💡 **Tip:** Use a combination of uppercase letters, lowercase letters, numbers, and special symbols to maximize password strength.",
    },
    "日本語": {
        "settings": "設定",
        "password_rules": "パスワードルール",
        "minimum_length": "最小文字数",
        "require_number": "数字を含める",
        "require_upper_lower": "大文字と小文字を含める",
        "require_length": "十分な長さを確保する（12文字以上）",
        "require_not_common": "よく使われるパスワードを避ける",
        "require_not_repeated": "連続・重複文字を避ける",
        "title": "🔐 パスワード強度チェッカー",
        "subtitle": "パスワードの安全性を診断・または強力なパスワードを自動生成します。",
        "password": "パスワードを入力",
        "check": "強度をチェック",
        "empty": "パスワードを入力してください！",
        "result": "診断結果",
        "strength": "強度レベル",
        "score": "スコア",
        "reason": "詳細フィードバック",
        "suggestions": "セキュリティに関するアドバイス",
        "tips": "💡 **ヒント:** 英大文字、小文字、数字、特殊記号を組み合わせて使用することで、解読されにくい強力なパスワードを作成できます。",
    },
}